### ISSUE TITLE
I know you've answered this before 

### ISSUE THREAD

**Issue by dougiebeatz** [mkafrin/mka-lasers#10]
Im having a terrible time getting the lasers to active period . 

- Ive been able to create a lazer , and its produced into the lazer.txt document 
- From here im a little lost ('@mka-lasers/client/client.lua',
    'your_scripts_client.lua', ) am i dropping both of these into the lets say for example BankHeist Fxmanifest ? 
 - If so awesome im on the right track 
 
 - Now the whole laser.active(true) where is that going ? do i take the part of code from the Lazer.txt file add it into the BankHeist Client side then add laser.active  . 
 
 Example 
 
 -- Name: legionbank | 2021-12-09T21:25:31Z
Laser.new()
  vector3(147.805, -1046.457, 28.597),
  {vector3(148.751, -1044.211, 28.471)},
  {travelTimeBetweenTargets = {1.0, 1.0}, waitTimeAtTargets = {0.0, 0.0}, randomTargetSelection = true, name = "legionbank"} 
)

Where would i add the extra getactive , get color , etc .  maybe by any chance can you release a quick video of you creating a laser ? 

thanks

**Comment by mkafrin** [comment]
It seems as though you've created your laser properly.
> From here im a little lost ('@mka-lasers/client/client.lua',
'your_scripts_client.lua', ) am i dropping both of these into the lets say for example BankHeist Fxmanifest ?

Yes, you need to put `@mka-lasers/client/client.lua` in the client_scripts section of your resource's fxmanifest.lua.

Then, you paste the code in lasers.txt into your resource, wherever you want to use it. After that, you call the methods like setActive, getColor, etc. ON the laser you create with Laser.new(). Example below:

```lua
-- Code from lasers.txt that creates an instance of a laser and stores it in the variable `laser`
local laser = Laser.new(
  vector3(147.805, -1046.457, 28.597),
  {vector3(148.751, -1044.211, 28.471)},
  {travelTimeBetweenTargets = {1.0, 1.0}, waitTimeAtTargets = {0.0, 0.0}, randomTargetSelection = true, name = "legionbank"}
)
-- Using methods on laser (in this case, calling setActive(true), which turns on the laser)
laser.setActive(true)
```

If you still have issues after this, please post your fxmanifest and script so I can see what you are doing.

**Comment by dougiebeatz** [comment]
Ah thank you so much , i appreciate your hard work and time .
