### ISSUE TITLE
How to trigger lasers?

### ISSUE THREAD

**Issue by chiefcycle** [mkafrin/mka-lasers#11]
Hey, I don't really know alot about scripting and I don't understand how to trigger the lasers. Can you give me an example?

**Comment by mkafrin** [comment]
If you don't know how to script and/or don't know lua, this probably isn't the tool for you. It isn't a gameplay tool, it's a scripting tool. If you do know those things, then read below.

Use the creation tool described in the [README](https://github.com/mkafrin/mka-lasers/blob/main/README.md#creation) to make a laser. That will generate a piece of code that creates a new laser. Take that code and store it in a variable and then call setActive(true) on it, like so:

```lua
local laser = -- *code that was generated placed here*
laser.setActive(true)
```
