### ISSUE TITLE
if playerBeingHit then SetPlayerWantedLevel 

### ISSUE THREAD

**Issue by xtxvxtx** [mkafrin/mka-lasers#12]
So I got the lasers working and they are so cool, now im trying to add a function to just add 

            SetPlayerWantedLevel(playerId, 4, false)
            SetPlayerWantedLevelNow(playerId, false)

to set a wanted level on player hit.
I tried this to no avail.

CreateThread(function()
    if playerBeingHit then
        local playerId = PlayerId()
            SetPlayerWantedLevel(playerId, 4, false)
            SetPlayerWantedLevelNow(playerId, false)
        -- Laser just hit the player
    else
        -- Laser just stopped hitting the player
        -- hitPos will just be a zero vector here
    end
end)

**Comment by mkafrin** [comment]
Please see the readme for how you properly use `onPlayerHit()` https://github.com/mkafrin/mka-lasers#using-onplayerhit. If you have the laser itself working then you probably just need to store it in a variable `local laser = Laser.new(...)` and then use the code in the linked example in the readme.

**Comment by mkafrin** [comment]
Closing this for now. Feel free to re-open if you have further questions @xtxvxtx.
