### ISSUE TITLE
Laser's Active but not visible

### ISSUE THREAD

**Issue by AaronH02** [mkafrin/mka-lasers#17]
when running through where the lasers have been setup its printing "person hit" as expected
however there are no lasers visible

FIX: REMOVED use_experimental_fxv2_oal 'yes' FROM MANIFEST

**Comment by AaronH02** [comment]
Fixed the issue above

Is there a way to make the lines thicker?

**Comment by mkafrin** [comment]
Hmm never seen that manifest thing before, but good to see removing it fixed the issue.

As for thickness, unfortunately the `DrawLine` native this resource uses does not have a thickness option. You can set the color of the laser, and setting the transparency/alpha lower can make the line look thinner, but there's not really any way to make them look thicker to my knowledge.
