### ISSUE TITLE
Lasers not showing 

### ISSUE THREAD

**Issue by EliasMatta** [mkafrin/mka-lasers#3]
Hey I found you from nopixel as developer and I seen you're using lasers in the big vault I wanted to try it out and I created my lasers and I followed your steps and it was not showing i created new resource with _resource.lua and put the client script code and i pasted the generated code to another file client.lua and when  i run server it not showing.

**Comment by mkafrin** [comment]
@EliasMatta The lasers aren't active by default, so after creating them with Laser.new() you must call setActive(true) on them to turn them on. That should probably be in the README, now that I think about it. Anyways, try that and let me know if it works.

**Comment by EliasMatta** [comment]
Oh yes it working thanks and also how do we use additional Laser Functions like if i press a Key i make a laser stop moving

**Comment by mkafrin** [comment]
All the additional laser functions listed [here](https://github.com/mkafrin/mka-lasers#other-laser-functions) are called on the laser itself once you create it with Laser.new(). If you want to have the laser stop moving on key press, simply check for keypress using the necessary native functions (IsControlJustPressed or w/e) and then call `laser.setMoving(false)`.
