### ISSUE TITLE
setActive step creates error

### ISSUE THREAD

**Issue by ImNorin** [mkafrin/mka-lasers#6]
I have completed the previous steps in the readme file. Also put `Laser.new()` in my client file. But when I try to call `setActive(true)` in the same lua file as my script is supposed to activate the lasers, all I get is an error: 
`SCRIPT ERROR: @vaultrobbery/client:53: attempt to call a nil value (field 'setActive')`

Hopefully I imported the script correctly. Followed your steps and put @ before the mentioned, which I assume means it import any folder in the resource folder(?) and doesnt have to be inside my vaultrobbery folder

**Comment by mkafrin** [comment]
> which I assume means it import any folder in the resource folder(?) and doesnt have to be inside my vaultrobbery folder

You would be correct. And if Laser.new() didn't throw an error, you imported it correctly.

It's hard to tell what could be going wrong from the lack of any code to look at, but my best guess is you're doing something like this (replace ... for w/e params you have of course)
```lua
Laser.new(...)
setActive(true)
```
but setActive is a method on the Laser object, which is returned by Laser.new(). So really it should be like this.
```lua
local laser = Laser.new(...)
laser.setActive(true)
```
If this isn't the issue, please post a snippet of the relevant code, so I can better understand what you're doing.

**Comment by ImNorin** [comment]
```
local laser = Laser.new(...)
laser.setActive(true)
```

This worked! Thank you 😄  I'm still learning how to code, so missed this easy but important step

**Comment by mkafrin** [comment]
No problem, enjoy learning how to code!
