### ISSUE TITLE
onPlayerHit error

### ISSUE THREAD

**Issue by NotNikolai** [mkafrin/mka-lasers#7]
When using onPlayerHit Function it returns StartShapeTestRay as nil

**Comment by NotNikolai** [comment]
Seems onPlayerHit dosnt work all as well.

**Comment by mkafrin** [comment]
Fixed in latest commit (11192ae24bb834c5c3fd1ee055ec1a28eb015dbc). Re-download/clone to get the fix.

**Comment by NotNikolai** [comment]
So these are named wrong, had to move to as they dont have the native list updated(?)

local ray = Citizen.InvokeNative(0x377906D8A31E5586, origin.x, origin.y, origin.z, destination.x, destination.y, destination.z, flags, nil, 0) return Citizen.InvokeNative(0x3D87450E15D9869, ray)

to stop getting the error. But its returning both newPlayerBeingHit, and PlayerBeingHit as nil now with those adjusted.
