### ISSUE TITLE
Still errors (Native Changes)

### ISSUE THREAD

**Issue by NotNikolai** [mkafrin/mka-lasers#8]
So with the latest commit you need to just Invoke the native as the names have changed (Im assuming) for StartShapeTestRay, StartExpensiveSynchronousShapeTestLosProbe and GetShapeTestResult

```
local function RayCast(origin, destination, flags)
  local ray = Citizen.InvokeNative(0x377906D8A31E5586, origin.x, origin.y, origin.z, destination.x, destination.y, destination.z, flags, nil, 0)
  return Citizen.InvokeNative(0x3D87450E15D9869, ray)
end

```

This still is causing issues with playerhit detection and returning everything as nil in your _onPlayerHitTest

`    local _, hit, hitPos, _, hitEntity = RayCast(origin, destination, 12)`

**Comment by mkafrin** [comment]
@NotNikolai What fx_version are you using in your fxmanifest.lua file? Because those natives have not had different names other than the ones I'm now checking for in like a year+.

**Comment by NotNikolai** [comment]
@mkafrin yeah i figured it out. Was on the wrong version. I would suggest though maybe only showing the lasers when your in a distance of them? Keep the resource ms down.

**Comment by mkafrin** [comment]
@NotNikolai I didn't want to make that decision for users, but you are more than welcome to use setVisible or setActive on the laser to do it yourself. If a laser is not active, no work will be done. If it's not visible, it won't be shown and the hit check won't happen either.

**Comment by NotNikolai** [comment]
yeah i did that. Still runs a around 0.02ms with lasers set to not visable. But i can find a way to optimize a bit more.

**Comment by NotNikolai** [comment]
also found another bug, sometimes the lasers just stop detecting the player being in them. Tried turning them off and on ect. Just stops detecting them hitting player.

**Comment by mkafrin** [comment]
> yeah i did that. Still runs a around 0.02ms with lasers set to not visable. But i can find a way to optimize a bit more.

setActive should be more performant. setVisible still has the interpolation of the laser happening in the background whereas setActive ends the whole laser thread.

> also found another bug, sometimes the lasers just stop detecting the player being in them. Tried turning them off and on ect. Just stops detecting them hitting player.

Yeah I'm gonna need more info or a way to reproduce to fix that haha. But if you have anymore info, make an issue for it.
