### ISSUE TITLE
Call setActive(true)

### ISSUE THREAD

**Issue by 0Henkka** [mkafrin/mka-lasers#9]
Can you make a example where you call setActive(true) I got only errors when I try to turn them on. Attempt to call nil value (field 'setActive'). I've tried Lazer.setActive(true), self.setActive(true) and setActive(true). My fxmanifest is ok and i have imported the lasers to my client file.

**Comment by mkafrin** [comment]
setActive is a method on the laser that is created. So first you create the laser, then you call setActive on it. Example below:

```lua
-- This would be the line that is generated in lasers.txt by the creation script (if you use it)
local laser = Laser.new(originPoint, targetPoints, { name = "laser_" .. tostring(k) })
-- Calling the setActive method on the laser
laser.setActive(true)
```

If you still get some error after doing this, please provide your code so I know better what's going on.

**Comment by 0Henkka** [comment]
i figured it out when i looked other resources that uses these lasers. When you generate the lasers it only does Laser.new...
It doesn't include local laser = but thanks still for the quick response.
